[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
[project] 
name = "Pp_structure" 
version = "0.1.0"
description = "Python project structure template"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []
[project.optional-dependencies]
dev = [ 
	"pytest", 
	"ruff",
]
